# FROM tensorflow/tensorflow:2.12.0-gpu
FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel
USER root:root

# RUN
RUN apt update
RUN apt upgrade -y --fix-missing
RUN apt install apt-utils
# RUN apt-get update && apt-get install zip
RUN apt-get update && apt-get install -y unzip

# RUN apt-get -y update
RUN apt-get -y install git

RUN python3 -m pip install -U setuptools pip
RUN python3 -m pip install transformers
RUN python3 -m pip install datasets
RUN python3 -m pip install accelerate
RUN python3 -m pip install boto3
RUN python3 -m pip install wget
RUN python3 -m pip install protobuf

# USER 1000:1000
